x-php-template: &php
  restart: 'always'
  networks:
    internal:
  volumes:
    - ${DOCUMENT_ROOT}:/var/www/html:rw
    - ./docker/config/php/php.ini:/usr/local/etc/php/php.ini
    - ./docker/config/php/docker-php-ext-xdebug3.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  environment: &php_env
    XDEBUG_MODE: debug
    XDEBUG_CONFIG: client_host=host.docker.internal
    XDEBUG_SESSION: PHPSTORM
networks:
  internal:
services:
  traefik:
    image: "traefik:v2.5"
    container_name: "${COMPOSE_PROJECT_NAME}-traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:${HOST_PORT_HTTP}"
      - "--providers.docker.network=internal"
    networks:
      - internal
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "${HOST_PORT_HTTP}:${HOST_PORT_HTTP}"
      - "${HOST_PORT_TRAEFIK}:8080"
  apache24:
    image: httpd:2.4
    container_name: '${COMPOSE_PROJECT_NAME}-apache'
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html:rw
      - ./docker/config/apache/vhosts:/usr/local/apache2/sites-enabled
      - ./docker/config/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./docker/data/logs/apache2:/var/log/apache2
    networks:
      - internal
    labels:
      - traefik.enable=true
#     php 8.1
      - traefik.http.routers.php81.rule=Host(`${COMPOSE_PROJECT_NAME}.php81.localhost`)
      - traefik.http.routers.php81.service=php81
      - traefik.http.services.php81.loadbalancer.server.port=8081
#     php 8.0
      - traefik.http.routers.php80.rule=Host(`${COMPOSE_PROJECT_NAME}.php80.localhost`)
      - traefik.http.routers.php80.service=php80
      - traefik.http.services.php80.loadbalancer.server.port=8080
  nginx:
    image: nginx:latest
    container_name: '${COMPOSE_PROJECT_NAME}-nginx'
    volumes:
      - ${DOCUMENT_ROOT}:/usr/share/nginx/html:rw
      - ./docker/config/nginx/vhosts/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/data/logs/nginx:/var/log/nginx
    networks:
      - internal
    labels:
      - traefik.enable=true
#     php 8.1
      - traefik.http.routers.ngx-php81.rule=Host(`${COMPOSE_PROJECT_NAME}.nginx.php81.localhost`)
      - traefik.http.routers.ngx-php81.service=php81
      - traefik.http.services.ngx-php81.loadbalancer.server.port=8081
#     php 8.0
      - traefik.http.routers.ngx-php80.rule=Host(`${COMPOSE_PROJECT_NAME}.nginx.php80.localhost`)
      - traefik.http.routers.ngx-php80.service=php80
      - traefik.http.services.ngx-php80.loadbalancer.server.port=8080
  php81:
    <<: *php
    build:
      context: ./docker/bin/php81
    container_name: '${COMPOSE_PROJECT_NAME}-php81'
    hostname: f3-php81
    environment:
      <<: *php_env
      PHP_IDE_CONFIG: serverName=${COMPOSE_PROJECT_NAME}.php81.localhost
  php80:
    <<: *php
    build:
      context: ./docker/bin/php80
    container_name: '${COMPOSE_PROJECT_NAME}-php80'
    hostname: f3-php80
    environment:
      <<: *php_env
      PHP_IDE_CONFIG: serverName=${COMPOSE_PROJECT_NAME}.php80.localhost
  mysql:
    image: mysql:5.7
    container_name: '${COMPOSE_PROJECT_NAME}-mysql'
    hostname: f3-mysql
    restart: 'always'
    ports:
      - "${HOST_PORT_MYSQL}:${MYSQL_PORT}"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
      - ./docker/data/logs/mysql:/var/log/mysql
    command: mysqld --general-log=1 --general-log-file=/var/log/mysql/general-log.log
    networks:
      internal:
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  pgsql:
    image: postgres:latest
    container_name: '${COMPOSE_PROJECT_NAME}-pgsql'
    hostname: f3-pgsql
    restart: 'always'
    ports:
      - "${HOST_PORT_PGSQL}:${PGSQL_PORT}"
    networks:
      internal:
    environment:
      POSTGRES_DB: ${PGSQL_DATABASE}
      POSTGRES_USER: ${PGSQL_USER}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: '${COMPOSE_PROJECT_NAME}-mssql'
    hostname: f3-mssql
    restart: 'always'
    networks:
      internal:
    ports:
      - "${HOST_PORT_MSSQL}:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 'fatfree-root'
      MSSQL_PID: 'Developer'
  redis:
    container_name: '${COMPOSE_PROJECT_NAME}-redis'
    hostname: f3-redis
    image: redis:latest
    networks:
      internal:
    ports:
      - "${HOST_PORT_REDIS}:6379"
  memcached:
    container_name: '${COMPOSE_PROJECT_NAME}-memcached'
    hostname: f3-memcached
    image: memcached:latest
    networks:
      internal:
